#!/bin/bash
set -x
echo -e "\e[33m ========================= AWS Project =========================\033[0m"
echo -e "\e[33m ========== Installing and Configuring T2micro in EC2 ==========\033[0m"
#
#Please modify for your preferences
#
#######################################################################################################################
echo -e "\n\e[33m --------------- Creating a key pair ---------------\033[0m\n"
# Change $mykeyname to your preferred one
aws ec2 create-key-pair --key-name mykeyname --query 'KeyMaterial' --output text > ~/.ssh/mykeyname.pem
#
chmod 400 ~/.ssh/mykeyname.pem
ssh-add ~/.ssh/mykeyname.pem
# Don't forget to have your security group be already configured for open ssh port
#######################################################################################################################
# The instances: ami-08182c55a1c188dee (Ubuntu 18); ami-075b44448d2276521 (Ubuntu 16.04) 
echo -e "\n\e[33m --------------- Create an Amazon EC2 instance ---------------\033[0m\n"
aws ec2 run-instances --image-id ami-id \
--key-name mykeyname --instance-type t2.micro \
--count 1 --security-group-ids mysg-id \
--user-data file://my_instance_configuration_script.sh

sleep 40s
instanceID=$(aws ec2 describe-instances \
--filters "Name=key-name,Values=mykeyname" \
--query "Reservations[*].Instances[*].InstanceId" \
--output=text)
instanceIp=$(aws ec2 describe-instances \
--query "Reservations[*].Instances[*].PublicIpAddress" \
--filters "Name=key-name,Values=mykeyname" \
--output=text)
# Create instance tag
aws ec2 create-tags --resources ami-id $instanceID --tags Key=Name,Value=myinstancetag

echo -e "\e[1;92m ----- Your Instance IP is $instanceIp -----\033[0m"

set +x
